### ISSUE TITLE
`FeatureMatrixExtractor` should return DataFrames with `bool` values for channels and phenotypes instead of `int`

### ISSUE THREAD

**Issue by CarlinLiao** [nadeemlab/SPT#206] opened 2023-09-12 21:35 UTC
DataFrames don't have the same limitation as SQL databases, so binary channel/phenotype-is-positive/negative values can be returned as `bool`s instead of 0/1 `int`s.

This won't make DataFrame console reporting any messier either because the latest change that renames channels from `F{i}` to `F {channel_symbol}` means that all the columns will print with inconsistent widths now anyway.

**Comment by jimmymathews** [comment] 2023-09-15 16:30
The 0/1 convention is not used due to database limitations, and it is not even the convention used in the database. And Postgres supports boolean values.

The 0/1 coding has its origin in the SQL query that pulls out the expression data, in [SparseMatrixPuller](https://github.com/nadeemlab/SPT/blob/dd93f8d080c5c500a8e7168b37ac2e372a764860/spatialprofilingtoolbox/workflow/common/sparse_matrix_puller.py#L255).

You're welcome to change this to boolean `true`/`false`, just check that the regression tests pass. The usage in `cache-expressions-data-array` with `CompressedMatrixWriter`would be affected, and perhaps other usages of `FeatureMatrixExtractor` would have to be checked as well for resilience to this change.

**Comment by jimmymathews** [comment] 2023-12-14 17:15
It seems you don't plan to work on this, closing unless it rises in priority for some reason.

**Closed by jimmymathews** 2023-12-14 17:15 UTC
Labels: wontfix, refactor
